name: Sync to Hugging Face hub
on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HG: ${{ secrets.HG }}
        run: git remote add space https://SorinAbrudan:$HG@huggingface.co/spaces/SorinAbrudan/ml-ops-demo
      - name: Push to hub
        env:
          HG: ${{ secrets.HG }}
        run: git push --force https://SorinAbrudan:$HG@huggingface.co/spaces/SorinAbrudan/ml-ops-demo main
